// @ts-check
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import eslintConfigPrettier from "eslint-config-prettier";

export default tseslint.config(
  {
    // src/planRegister/vendored/ is generated byte-for-byte by
    // sync_shared_unit.ts's --check drift mode (RU-012, node P2-N010)
    // from the canonical copy in majodali/project-orchestrator — not
    // subject to this repository's own lint config, the same reason
    // it is excluded from Prettier (see .prettierignore).
    ignores: [
      "dist/**",
      "node_modules/**",
      "coverage/**",
      "src/planRegister/vendored/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  eslintConfigPrettier,
  {
    languageOptions: {
      parserOptions: {
        project: "./tsconfig.eslint.json",
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
);
